version: '3.7'
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"  # kibana
      - "9200:9200"  # elastic
      - "5044:5044"  # logstash
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch

  filebeat:
    image: elastic/filebeat:7.17.0
    volumes:
      - ./filebeat-config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/usr/share/filebeat/logs:ro
    depends_on:
      - elk